### ISSUE TITLE
connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by SaurabhBagade** [veryacademy/django-ecommerce-project-v2#2]
Hey, I cannot connect to Postgres DB running on docker. Actually, I copied all the code and then also I am unable to connect to Postgres.
It always throws me an error saying "password authentication failed" could you please resolve this for me.
I think that Postgres might be hashing the password. 
Thanks In advance.

**Comment by shakori999** [comment]
I guess we need to see your code for some files like dockerfile , docker-compose, django settings , what commands you used , and the output of these commands

**Comment by SaurabhBagade** [comment]
Actually I resolved the issue . The problem was that for some reason my docker postgres image was not running, so after long research I found that there is a alpine Linux version of postgres so I installed a postgres-alpine image from docker and it started working.
Postgres needs an OS to run on, so that was the problem

**Comment by shakori999** [comment]
great !! now you can close the issue, which is you don't longer need it anymore
