### ISSUE TITLE
ValidationError on datetime format in mydata.json

### ISSUE THREAD

**Issue by ossScharom** [veryacademy/django-ecommerce-project-v2#3]
Executing the test suite with the fixtures provided by the file `part-2/mydata.json` throws the following exception:

`E       django.core.exceptions.ValidationError: ['“14:18.33” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']`

**Comment by zander9648** [comment]
14:18.33 should it be 14:18:33 missing the second semi-colon

**Comment by zander9648** [comment]
try and few out first before scaling up if that helps
